// front-end/src/app/auth/login/login.component.ts
import { Component, OnInit } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import {
  FormGroup,
  FormBuilder,
  Validators,
  AbstractControl,
} from '@angular/forms';
import { catchError } from 'rxjs/operators';
import { of } from 'rxjs';
import { ConfigService } from '../config.service';

@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.css'],
})
export class LoginComponent implements OnInit {
  loginForm: FormGroup;
  loading: boolean;
  errorMsg: string;

  constructor(
    private formBuilder: FormBuilder,
    private httpClient: HttpClient,
    private configService: ConfigService
  ) {
    this.loginForm = this.formBuilder.group({
      username: ['', [Validators.required]],
      password: ['', [Validators.required]],
    });
    this.loading = false;
    this.errorMsg = '';
  }

  get username() {
    return this.loginForm.get('username') as AbstractControl;
  }

  get password() {
    return this.loginForm.get('password') as AbstractControl;
  }

  ngOnInit(): void {
    this.loginForm = this.formBuilder.group({
      username: ['', [Validators.required]],
      password: ['', [Validators.required]],
    });
    this.loading = false;
    this.errorMsg = '';
  }

  login() {
    this.loading = true;
    this.httpClient
      .post('http://localhost:3000/api/auth/login', {
        ...this.loginForm.value,
      })
      .toPromise()
      .then((data) => {
        const { access_token } = data as any;
        this.configService.setToken(access_token);
        this.loading = false;
      })
      .catch((err) => {
        this.errorMsg = err.error.message;
        this.loading = false;
      });
  }
}

<div>
  <div>
    <h2>Login</h2>
  </div>
  <div>
    <div *ngIf="loading; else loadingBlock">
      Loading...
    </div>
    <ng-template #loadingBlock>
      <form [formGroup]="loginForm" (submit)="login()">
        <div>
          <label for="username">Username</label><br />
          <input
            formControlName="username"
            type="text"
            placeholder="Username"
            required
          />
          <span *ngIf="username.invalid && username.touched">
            The username is required
          </span>
        </div>
        <div>
          <label for="password">Password</label><br />
          <input
            formControlName="password"
            type="password"
            placeholder="Password"
            required
          />
          <span *ngIf="password.invalid && password.touched">
            The password is required
          </span>
        </div>
        <div>
          <button type="submit" [disabled]="loginForm.invalid">Login</button>
        </div>
      </form>
    </ng-template>
  </div>
  <div *ngIf="errorMsg">
    <p>
      {{ errorMsg }}
    </p>
  </div>
</div>

// webapp/src/views/auth/Login.vue
<template>
  <div class="login-view">
    <h2>Login</h2>
    <hr />
    <div v-if="!loading">
      <form @submit.prevent="login()">
        <div>
          <label for="username">Username</label><br>
          <input
            v-model="username"
            type="text"
            placeholder="Username"
            required
          />
        </div>
        <div>
          <label for="password">Password</label><br>
          <input
            v-model="password"
            type="password"
            placeholder="Password"
            required
          />
        </div>
        <div>
          <button :disabled="formInvalid">Login</button>
          <br>
          <router-link to="/auth/signup"
            >Don't have an account? Signup</router-link
          >
        </div>
      </form>
      <div v-if="error">
        <p>Username doesn't exists</p>
      </div>
    </div>
    <div v-else>Loading...</div>
  </div>
</template>

<script>
import { mapMutations } from 'vuex';
import axios from 'axios';

export default {
  name: 'Login',
  data: () => ({
    username: '',
    password: '',
    loading: false,
    error: null,
  }),
  methods: {
    ...mapMutations(['setAccessToken']),
    async login() {
      this.loading = true;
      try {
        const data = await axios
          .post('http://localhost:3000/api/auth/login', {
            username: this.username,
            password: this.password,
          })
          .then((res) => res.data);
        this.setAccessToken(data.access_token);
        this.loading = false;
        this.$router.push({ path: '/' });
      } catch (err) {
        this.error = err;
        console.log(err)
        this.loading = false;
      }
    },
  },
  computed: {
    formInvalid() {
      return this.password == '' && this.username == ''
    }
  }
};
</script>
