// front-end/src/app/auth/signup/signup.component.ts
import { Component, OnInit } from '@angular/core';
import {
  FormGroup,
  FormBuilder,
  Validators,
  AbstractControl,
} from '@angular/forms';
import { HttpClient } from '@angular/common/http';
import { catchError } from 'rxjs/operators';
import { of } from 'rxjs';
import { ConfigService } from '../config.service';

@Component({
  selector: 'app-signup',
  templateUrl: './signup.component.html',
  styleUrls: ['./signup.component.css'],
})
export class SignupComponent implements OnInit {
  signupForm: FormGroup;
  loading: boolean;
  errorMsg: string;

  constructor(
    private formBuilder: FormBuilder,
    private httpClient: HttpClient,
    private configService: ConfigService
  ) {
    this.signupForm = this.formBuilder.group({
      username: ['', [Validators.required]],
      password: ['', [Validators.required]],
    });
    this.loading = false;
    this.errorMsg = '';
  }

  get username() {
    return this.signupForm.get('username') as AbstractControl;
  }

  get password() {
    return this.signupForm.get('password') as AbstractControl;
  }

  ngOnInit(): void {
    this.signupForm = this.formBuilder.group({
      username: ['', [Validators.required]],
      password: ['', [Validators.required]],
    });
  }

  signup() {
    this.loading = true;
    this.httpClient
      .post('http://localhost:3000/api/auth/signup', {
        ...this.signupForm.value,
      })
      .toPromise()
      .then((data) => {
        const { access_token } = data as any;
        this.configService.setToken(access_token);
        this.loading = false;
      })
      .catch((err) => {
        this.errorMsg = err.error.message;
        this.loading = false;
      });
  }
}

<div>
  <div>
    <h2>Signup</h2>
  </div>
  <div>
    <div *ngIf="loading; else loadingBlock">
      Loading...
    </div>
    <ng-template #loadingBlock>
      <form [formGroup]="signupForm" (submit)="signup()">
        <div>
          <label for="username">Username</label><br />
          <input
            formControlName="username"
            type="text"
            placeholder="Username"
            required
          />
          <span *ngIf="username.invalid && username.touched">
            The username is required
          </span>
        </div>
        <div>
          <label for="password">Password</label><br />
          <input
            formControlName="password"
            type="password"
            placeholder="Password"
            required
          />
          <span *ngIf="password.invalid && password.touched">
            The password is required
          </span>
        </div>
        <div>
          <button type="submit" [disabled]="signupForm.invalid">Signup</button>
        </div>
      </form>
    </ng-template>
  </div>
  <div *ngIf="errorMsg">
    <p>
      {{ errorMsg }}
    </p>
  </div>
</div>

// webapp/src/views/auth/Signup.vue
<template>
  <div class="signup-view">
    <h2>Signup</h2>
    <hr />
    <div v-if="!loading">
      <form @submit.prevent="signup()">
        <div>
          <label for="username">Username</label><br>
          <input
            v-model="username"
            type="text"
            placeholder="Username"
            required
          />
        </div>
        <div>
          <label for="password">Password</label><br>
          <input
            v-model="password"
            type="password"
            placeholder="Password"
            required
          />
        </div>
        <div>
          <button :disabled="formInvalid">Signup</button>
          <br>
          <router-link to="/auth/login"
            >Already have an account? Login</router-link
          >
        </div>
      </form>
      <div v-if="error">
        <p>Username doesn't exists</p>
      </div>
    </div>
    <div v-else>Loading...</div>
  </div>
</template>

<script>
import { mapMutations } from 'vuex';
import axios from 'axios';

export default {
  name: 'Signup',
  data: () => ({
    username: '',
    password: '',
    loading: false,
    error: null,
  }),
  methods: {
    ...mapMutations(['setAccessToken']),
    async signup() {
      this.loading = true;
      try {
        const data = await axios
          .post('http://localhost:3000/api/auth/signup', {
            username: this.username,
            password: this.password,
          })
          .then((res) => res.data);
        this.setAccessToken(data.access_token);
        this.loading = false;
        this.$router.push({ path: '/' });
      } catch (err) {
        this.error = err;
        console.log(err)
        this.loading = false;
      }
    },
  },
  computed: {
    formInvalid() {
      return this.password == '' && this.username == ''
    }
  }
};
</script>
